- hosts: CPP17Dev
  vars:
#   custom_repo: true
#   deploy_iptables: true
#   envir: prod
# vars_files:
#   - ~/RHACCOUNT
  become: yes
  become_method: sudo

  pre_tasks:

  tasks:
    - name: Get Updates
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Guest Additions
      apt:
        name:
          - virtualbox-guest-utils
          - virtualbox-guest-dkms
          - virtualbox-guest-x11
        state: present
        force_apt_get: true
        autoremove: true

    - name: Install Desktop Components (GUI)
      apt:
        name: 
          - ubuntu-desktop # Untiy (default)
#  shell: add-apt-repository ppa:kubuntu-ppa/backports
#         - kubuntu-desktop # KDE
#         - lubuntu-desktop # LXDE (Lubuntu) 
#         - cinnaon-desktop-environment # Cinnamon
#         - ubuntu-mate-desktop # MATE
#         - ubuntu-gnome-desktop # GNOME
#         - xubuntu-desktop # XFCE
#  apt install xfce4 slim
#  service slim start
        state: present
        force_apt_get: true
        autoremove: true

#   - name: Add ppa repository
#     shell: add-apt-repository ppa:jonathonf/gcc-7.1

    - name: Install gcc/g++ 7.1
      apt:
        name: 
          - gcc-7
          - g++-7
        state: present
        force_apt_get: true

    - name: Update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install QT 5.14.x prerequisite build-essential
      apt:
        name: 
          - build-essential
          - libfontconfig1
          - mesa-common-dev
        state: present
        cache_valid_time: 1800
        force_apt_get: true

    - name: Get QT 5.14.1
      get_url:
        url: http://download.qt.io/official_releases/qt/5.14/5.14.1/qt-opensource-linux-x64-5.14.1.run
        dest: /tmp/qt-opensource-linux-x64-5.14.1.run
        mode: '0755'
#     shell: wget http:/download/qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run -O /tmp/qt-opensource-linux-x64-5.7.0.run

#   - name: Install JAVA OpenJDK 1.8
#     shell: yum install java-1.8.0-openjdk java-1.8.0-openjdk-devel -y

  roles:
#   - epel7
#   - emacs7
#   - openjdk1.8
#   - odbc7
#   - postgresql-client
#   - devtools7
#   - python2RH7
#   - python3RH7
#   - pyenvRH7

  post_tasks:
#   - name: register mime types
#     shell: update-mime-database /usr/share/mime/packages/

#   - name: remove RHEL7.5
#     command:  "/usr/bin/subscription-manager remove --all"
#   - name: unregister RHEL7.5
#     command:  "/usr/bin/subscription-manager unregister"
#   - name: clean RHEL7.5
#     command:  "/usr/bin/subscription-manager clean"7
